// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gimtxpbrjujrnotgbuzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpbXR4cGJyanVqcm5vdGdidXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDAzNDAsImV4cCI6MjA2MDIxNjM0MH0.wYJuSiEbUygp4PKbRQx2k4ZaX5SG0ghlFWXaEKO1h0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);